import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { Providers } from "./providers";
import LanguageSelector from "./components/LanguageSelector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Immuno Lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col antialiased ${geistSans.variable} ${geistMono.variable}`}>
        <Providers>

          {/* ── Navbar ── */}
          <header style={{
            backgroundColor: "#1a5319",
            position: "sticky",
            top: 0,
            zIndex: 50,
            width: "100%",
          }}>
            <nav style={{
              maxWidth: "1400px",
              margin: "0 auto",
              height: "70px",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              padding: "0 40px",
            }}>
              {/* Logo */}
              <Link href="/" style={{
                fontSize: "22px",
                fontWeight: 700,
                color: "#ffffff",
                textDecoration: "none",
                whiteSpace: "nowrap",
                fontFamily: "Poppins, Helvetica, sans-serif",
              }}>
                ImmunoLab
              </Link>

              {/* Center links */}
              <div style={{ display: "flex", gap: "48px" }}>
                {[
                  { href: "/orders", label: "Order" },
                  { href: "/about", label: "About" },
                  { href: "/contact", label: "Contact Us" },
                ].map(({ href, label }) => (
                  <Link key={href} href={href} style={{
                    fontSize: "16px",
                    fontWeight: 600,
                    color: "#ffffff",
                    textDecoration: "none",
                    fontFamily: "Poppins, Helvetica, sans-serif",
                  }}>
                    {label}
                  </Link>
                ))}
              </div>

              {/* Auth + Language */}
              <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                <LanguageSelector />
                <Link href="/login" style={{
                  padding: "8px 24px",
                  borderRadius: "6px",
                  backgroundColor: "#4a7c4e",
                  color: "#ffffff",
                  fontSize: "15px",
                  fontWeight: 600,
                  textDecoration: "none",
                  fontFamily: "Poppins, Helvetica, sans-serif",
                }}>
                  Sign in
                </Link>
                <Link href="/register" style={{
                  padding: "8px 24px",
                  borderRadius: "6px",
                  backgroundColor: "#ffffff",
                  color: "#000000",
                  fontSize: "15px",
                  fontWeight: 600,
                  textDecoration: "none",
                  border: "2px solid #cccccc",
                  fontFamily: "Poppins, Helvetica, sans-serif",
                }}>
                  Register
                </Link>
              </div>
            </nav>
          </header>

          {/* ── Page content ── */}
          <main className="flex-grow">{children}</main>

          {/* ── Footer ── */}
          <footer style={{
            backgroundColor: "#1a5319",
            padding: "40px",
          }}>
            <div style={{
              maxWidth: "1400px",
              margin: "0 auto",
              display: "flex",
              justifyContent: "space-between",
              alignItems: "flex-start",
            }}>
              <div>
                <p style={{ margin: "0 0 6px 0", color: "#ffffff", fontSize: "15px", fontWeight: 600, fontFamily: "Poppins, Helvetica, sans-serif" }}>
                  ImmunoLab@gmail.com
                </p>
                <p style={{ margin: 0, color: "#ffffff", fontSize: "15px", fontWeight: 600, fontFamily: "Poppins, Helvetica, sans-serif" }}>
                  +777 777 777 7777
                </p>
              </div>
              <div style={{ display: "flex", gap: "32px" }}>
                <Link href="/privacy" style={{ color: "rgba(255,255,255,0.75)", fontSize: "15px", fontWeight: 600, textDecoration: "none", fontFamily: "Poppins, Helvetica, sans-serif" }}>
                  Privacy Policy
                </Link>
                <Link href="/terms" style={{ color: "rgba(255,255,255,0.75)", fontSize: "15px", fontWeight: 600, textDecoration: "none", fontFamily: "Poppins, Helvetica, sans-serif" }}>
                  Terms
                </Link>
              </div>
            </div>
          </footer>

          <Toaster />
        </Providers>
      </body>
    </html>
  );
}