import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Immuno Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col antialiased">
        <header className="border-b border-white/10 px-6 py-4">
         <nav className="flex justify-between items-center">
            <div className="flex space-x-6">
              <Link href="/" className="font-medium">
                Home
              </Link>

              <Link href="/posts" className="font-medium">
                Posts
              </Link>
            </div>
            <div className="flex space-x-6">
              <Link href="/users" className="font-medium">
                Log in
             </Link>
              <Link href="/users" className="font-medium">
               Sign in
              </Link>
            </div> 
            
          </nav>
        </header>


        <main className="flex-grow px-6 py-4">
          {children}
        </main>

        <footer className="border-t border-white/10 px-6 py-4 text-center">
          Footer
        </footer>
      </body>
    </html>
  );
}

