import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Providers } from "./providers";
import LanguageSelector from "./components/LanguageSelector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Immuno Lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col antialiased ${geistSans.variable} ${geistMono.variable}`}>
      <Providers> 
      <header className="sticky top-0 z-50 bg-white border-b border-black/10 px-6 py-4">
          <nav className= "navbar flex justify-between items-center">
            <div className="flex space-x-6">


              <div>
                <Link href = "/">
                  <Image
                    src="/logo.png"
                    alt="ImmunoLab logo"
                    width={200}
                    height={200}
                    priority
                    />
                </Link>

            </div>
                
              </div>

              <div className ="flex justify-center">
                <Link href=""></Link>
                <Link href="/posts" className="font-medium">Posts</Link>
              </div>

            <div className="flex space-x-6">
              <Link href="/orders" className="font-medium">Orders</Link>
              <Link href="/contact" className="font-medium">Contact Us</Link>
              <Link href="/" className="font-medium">About</Link>
            </div>

              <div className="flex space-x-6 items-center">
                <LanguageSelector />
                <Link href="/login" className="font-medium">Sign in</Link>
                <Link href="/register" className="font-medium">Register</Link>
              </div>
            
            </nav>
          </header>

          <main className="flex-grow px-6 pt-4">{children}</main>

          <footer className="footer border-t border-white/10 px-6 py-4 text-center">
            Footer
          </footer>
        </Providers>
      </body>
    </html>
  );
}
