import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Immuno Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-white/10 px-6 py-4">
          <nav className="flex space-x-6">
            <Link href="/" className="text-grey-800 font-medium">
              Home
            </Link>
            <Link href="/posts" className="text-grey-800 duration-200 font-medium">
              Posts
            </Link>
          </nav>
        </header>
        {children}

        <footer className="mt-auto border-t border-white/10 px-6 text-center">
          Footer
        </footer>
      </body>
    </html>
  );
}
